package app.runefolio.sync;

final class RuneFolioDataSharing
{
    private RuneFolioDataSharing() { }
    static final String SPOOL_LIMITS = RuneFolioScreenshotSpool.MAX_FILES + " pictures / " + (RuneFolioScreenshotSpool.MAX_BYTES >> 20) + " MiB";
    static final String UNLOCKS = "<html><body style='width:360px'>Change account-unlock sharing?<br><br>When enabled, RuneFolio sends supported route, bank-construction, spellbook, shortcut and area unlocks, plus sightings of selected checklist items in your inventory/equipment or an opened bank, to https://runefolio.app.<br><br>Only checklist IDs, evidence and timestamps are sent. Item sightings mean previously obtained, not current ownership. The connected account or temporary-code issuer receives the data and controls website sharing. Pending observations use the local retry queue. Turning this off stops new capture, not queued uploads or stored history.</body></html>";
    static final String PVP = "<html><body style='width:360px'>Change PvP history sharing?<br><br>When enabled, RuneFolio sends your observed finishing blows, defeated player names, dates and observed loot items/quantities/GE estimates to https://runefolio.app. Loot-key contents require native Loot Tracker and remain unassigned to opponents.<br><br>No opponent gear or locations are collected. Results are observations, not authoritative kill credit or net profit. The connected account (or temporary-code issuer) receives this data and controls website sharing. Turning this off stops new capture; queued uploads and server history remain.</body></html>";

    static final String CONNECT_QUESTION = "Continue to connect?";
    static final String CONNECTION = "RuneFolio sends data to https://runefolio.app, a third-party service independent of RuneLite and Jagex.\n\n"
        + "Connecting enables upload of character names, a derived character identity, skill XP/levels, quest and diary progress, combat achievements, Collection Log progress, and sync timestamps. Enabled loot and completion-history settings also send rewards and boss/raid, clue and Slayer results.\n\n"
        + "Bank/inventory/equipment snapshots, PvP history and screenshots are optional and off by default. Account-unlock observations are on by default and can be turned off in the plugin settings. Unlock observations include supported game flags and sightings of selected checklist items; they do not prove current ownership. PvP history includes your observed finishing blows, opponent names, timestamps and observed loot; loot keys are unassigned rewards. No opponent gear or location is collected. Existing enabled settings continue to apply when reconnecting. Screenshots may contain visible personal information; chat hiding does not mask every interface.\n\n"
        + "Account login sends data to the connected RuneFolio account. A temporary code sends that character's data to the account that issued the code. The receiving account controls website sharing.\n\n"
        + "Events are queued locally for retries and can only be sent under the connection that recorded them. Queued events and the connection token are kept in your RuneLite profile settings; if you enabled RuneLite profile cloud sync they are synced with that profile like any other setting. Turning a collector off stops new capture, but queued uploads and server history remain. Disconnect or revoke the connection to stop authorized uploads. RuneFolio does not request your Jagex password.\n\n"
        + "Screenshots are saved on this computer as compressed images with character/event metadata until acknowledged. The local queue survives restarts, is not encrypted, and is limited to " + SPOOL_LIMITS + ". It is shared by clients using this RuneLite settings folder. New captures may be skipped when full. Clear local screenshot queue removes waiting/held copies, not website images.\n\n"
        + CONNECT_QUESTION;

    static final String BANK = "<html><body style='width:360px'>Change bank and wealth sharing?<br><br>When enabled, this sends bank, inventory and equipment item names, IDs, quantities and estimated values to https://runefolio.app when you open your bank.<br><br>"
        + "Data goes to the connected account (or temporary-code owner's account). Pending snapshots are saved locally for retries in your RuneLite profile settings and follow RuneLite profile cloud sync if you enabled it. Turning this off stops new capture; queued uploads and server history remain.</body></html>";
    static final String SCREENSHOTS = "<html><body style='width:360px'>Change screenshot sharing?<br><br>When enabled, this captures selected in-game moments and uploads compressed screenshots to https://runefolio.app.<br><br>"
        + "Images go to the connected account (or temporary-code owner's account) and follow its website sharing settings. Images can contain visible personal information. Chat hiding does not mask every interface.<br><br>Compressed images and event metadata are saved unencrypted on this computer for retries, up to " + SPOOL_LIMITS + ", and survive restart. Turning this off stops new capture, not queued uploads. Clear local screenshot queue deletes local waiting/held copies only. Existing website images remain.</body></html>";
    static final String LOOT = "<html><body style='width:360px'>Change loot sharing?<br><br>When enabled, this sends observed loot sources, item names/IDs, quantities, values and timestamps from RuneLite's Loot Tracker to https://runefolio.app.<br><br>"
        + "Loot from a defeated player is attributed to their name only when Sync PvP history is also enabled; otherwise it is recorded as coming from an unnamed PvP opponent.<br><br>"
        + "Data goes to the connected account (or temporary-code owner's account). Turning this off stops new loot capture; queued uploads and server history remain.</body></html>";
    static final String COMPLETIONS = "<html><body style='width:360px'>Change completion-history sharing?<br><br>When enabled, this sends observed boss/raid, clue and Slayer completions, timestamps and available counts, times, party sizes, points and rewards to https://runefolio.app.<br><br>"
        + "Data goes to the connected account (or temporary-code owner's account). Turning this off stops new completion capture; queued uploads and server history remain.</body></html>";
}
