displayName=RuneFolio Sync
author=Brettgod1355
description=RuneFolio character connection client
tags=runefolio,progress,tracker,loot
version=0.3.52
plugins=app.runefolio.sync.RuneFolioPlugin
build=standard
