displayName=RuneFolio Sync
author=RuneFolio
description=Private-alpha RuneFolio character connection client.
tags=runefolio,progress,tracker,loot
version=0.3.26
plugins=app.runefolio.sync.RuneFolioPlugin
build=standard
