import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { notification, publicSummary } from './notify-discord.mjs';
test('only explicit public notes are posted; internal body sections and closed-unmerged PRs are excluded', () => {
  const body = '## Summary\nInternal implementation details\n## Discord changelog message\n- The calendar now opens the selected day.\n## Validation\nPrivate diagnostic notes';
  assert.equal(publicSummary(body), '- The calendar now opens the selected day.');
  const pr = { number: 4, merged:true, merge_commit_sha:'a'.repeat(40), title:'feat: Better calendar', body, base:{ref:'main',repo:{full_name:'example/site'}} };
  const result = notification({pull_request:pr},'website','example/site','1');
  assert.equal(result.kind,'merge'); assert.equal(result.title,'Better calendar'); assert.ok(!JSON.stringify(result).includes('diagnostic'));
  assert.equal(notification({pull_request:{...pr,merged:false}},'website','example/site','1'),null);
  assert.equal(notification({pull_request:{...pr,body:'Technical-only notes'}},'website','example/site','1').code,'missing_changelog');
  assert.equal(publicSummary('## Discord changelog message\n@everyone see this update'),null);
  assert.equal(publicSummary('## Discord changelog message\n@here see this update'),null);
  assert.equal(publicSummary('## Discord changelog message\n<!-- Write a summary here -->\n'),null);
  assert.equal(publicSummary('## Discord changelog message\nFixed a bug in the @Inject-annotated field.'),'Fixed a bug in the @Inject-annotated field.');
  assert.equal(notification({pull_request:{...pr,title:'fix: @Inject field bug'}},'website','example/site','1').title,'@Inject field bug');
});
test('a trailing attribution footer after the changelog paragraph does not poison the extracted summary', () => {
  const withFooter = '## Discord changelog message\n\nFixed a timeout that could interrupt background sync.\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n\nhttps://claude.ai/code/session_abc\n\n---\n_Generated by [Claude Code](https://claude.ai/code/session_abc)_';
  assert.equal(publicSummary(withFooter), 'Fixed a timeout that could interrupt background sync.');
});
test('CI notifications only accept failed main-branch runs from the correct repository', () => {
  const run={id:8,conclusion:'failure',head_branch:'main',head_repository:{full_name:'example/site'}};
  assert.equal(notification({workflow_run:run},'website','example/site','1').code,'ci_failed');
  for(const patch of [{head_branch:'feature'},{conclusion:'success'},{head_repository:{full_name:'fork/site'}}]) assert.equal(notification({workflow_run:{...run,...patch}},'website','example/site','1'),null);
});
test('the notification workflow reads the manager origin from a secret, never a variable', async () => {
  const workflow = await readFile(new URL('../.github/workflows/discord-notifications.yml', import.meta.url), 'utf8');
  assert.doesNotMatch(workflow, /vars\.DISCORD_EVENTS_URL/, 'a repository variable is printed in clear in the job log');
  assert.match(workflow, /DISCORD_EVENTS_URL: \$\{\{ secrets\.DISCORD_EVENTS_URL \}\}/);
  assert.match(workflow, /steps\.config\.outputs\.configured == 'true'/, 'sending steps stay gated on the secret being set');
});
